/**
 * Settings → Remote pi worker: where the agent reaches a pi installed on
 * another host, over SSH only.
 *
 * Unlike Codex and Claude workers, nothing runs inside the app-server for this
 * integration: the BFF itself shells out to `ssh` (see `runner.ts`), so the
 * settings live on the BFF's own `bff-data` volume and never cross the upstream
 * connection. The private key is lettuce-held: generated by the BFF
 * (`PiService.generateKeyPair`, the recommended path) or pasted, stored 0600 on
 * that volume, and never returned to a browser. The browser sees
 * `PublicPiSettings`: `hasKey` plus the PUBLIC half (`publicKey`) — a public key
 * is safe to serve, and it is exactly the line the operator pastes into the
 * remote host's `authorized_keys`.
 *
 * (An ssh-agent auth mode existed on this branch and was dropped by operator
 * decision on 2026-10-06: unattended simplicity over zero-storage custody.)
 *
 * `pathPrepend` is not cosmetic: a non-interactive remote shell gets a minimal
 * PATH that usually misses pi and node entirely (spike finding,
 * docs/remote-pi-plan.md § 3.1), so the dispatch command carries a PATH
 * prefix. It is normalized on the way in and on the way out because a trailing
 * slash is a natural thing to type and a *program* can see it: PATH search
 * composes `$dir/pi`, and a launcher that finds its own install directory by
 * stripping path elements off `$0` lands one level off (`bin//pi` → `bin`
 * instead of `agent`) and fails naming a file nobody asked for.
 */

/** Collapse a typed PATH prefix to what a PATH search should actually use. */
export function normalizePathPrepend(value: string): string {
  return value
    .split(":")
    .map((entry) => entry.trim().replace(/\/+$/, ""))
    .filter((entry) => entry !== "")
    .join(":");
}

export interface PiSettings {
  /** Whether the pi tools exist at all (the `pi` profile token must also be on). */
  enabled: boolean;
  host: string;
  port: number;
  user: string;
  /** Private key in PEM text form. Held by lettuce, never returned to a browser. */
  privateKey: string | null;
  /**
   * Who made the stored key: lettuce (`generateKeyPair`) or a paste. The
   * Settings form shows one flow at a time and must not claim it generated a
   * key it was handed; never inferred from the PEM, only recorded when it
   * happens.
   */
  keySource: "generated" | "pasted";
  /**
   * Public half, derived or generated by the service (never trusted from the
   * browser). Safe to serve: this is the `authorized_keys` line for the remote.
   */
  publicKey: string | null;
  /** Prepended to PATH in every remote command, e.g. `/opt/node/bin:/opt/pi/bin`. */
  pathPrepend: string;
  /** Absolute directory pi runs in on the remote host. */
  workdir: string;
  /** Optional pi model id; null lets the remote pi use its own default. */
  model: string | null;
}

/** What the browser sees: the key is reduced to whether one is set. */
export type PublicPiSettings = Omit<PiSettings, "privateKey"> & { hasKey: boolean };

export const DEFAULT_PI_SETTINGS: PiSettings = {
  enabled: false,
  host: "",
  port: 22,
  user: "",
  privateKey: null,
  keySource: "generated",
  publicKey: null,
  pathPrepend: "",
  workdir: "",
  model: null,
};

export class InvalidPiSettingsError extends Error {}

export function toPublicPiSettings(settings: PiSettings): PublicPiSettings {
  const { privateKey, ...rest } = settings;
  return { ...rest, hasKey: privateKey !== null };
}

/** Lenient: a missing, hand-edited or older file still loads, with defaults filling gaps. */
export function parsePiSettings(text: string | null): PiSettings {
  if (!text) return { ...DEFAULT_PI_SETTINGS };
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    return { ...DEFAULT_PI_SETTINGS };
  }
  if (!raw || typeof raw !== "object") return { ...DEFAULT_PI_SETTINGS };
  const r = raw as Record<string, unknown>;
  return {
    enabled: r.enabled === true,
    host: typeof r.host === "string" ? r.host : "",
    port: typeof r.port === "number" && r.port >= 1 && r.port <= 65535 ? r.port : 22,
    user: typeof r.user === "string" ? r.user : "",
    privateKey: typeof r.privateKey === "string" && r.privateKey ? r.privateKey : null,
    keySource: r.keySource === "pasted" ? "pasted" : "generated",
    publicKey: typeof r.publicKey === "string" && r.publicKey ? r.publicKey : null,
    pathPrepend: typeof r.pathPrepend === "string" ? normalizePathPrepend(r.pathPrepend) : "",
    workdir: typeof r.workdir === "string" ? r.workdir : "",
    model: typeof r.model === "string" && r.model ? r.model : null,
  };
}

export function renderPiSettings(settings: PiSettings): string {
  return `${JSON.stringify(settings, null, 2)}\n`;
}

/**
 * Merge a browser update into the saved settings. `privateKey` is only
 * replaced when the body carries a non-empty string — an absent or empty one
 * keeps the stored key, so the form can show `hasKey` without holding the key.
 * Throws InvalidPiSettingsError on anything unusable.
 */
export function applyPiSettingsUpdate(current: PiSettings, body: unknown): PiSettings {
  if (!body || typeof body !== "object") throw new InvalidPiSettingsError("Expected a JSON object");
  const r = body as Record<string, unknown>;

  const next: PiSettings = { ...current };
  if ("enabled" in r) {
    if (typeof r.enabled !== "boolean")
      throw new InvalidPiSettingsError("`enabled` must be true or false");
    next.enabled = r.enabled;
  }
  if (typeof r.host === "string") next.host = r.host.trim();
  if (typeof r.user === "string") next.user = r.user.trim();
  if ("port" in r) {
    const port = Number(r.port);
    if (!Number.isInteger(port) || port < 1 || port > 65535) {
      throw new InvalidPiSettingsError("`port` must be 1-65535");
    }
    next.port = port;
  }
  if ("pathPrepend" in r) {
    if (typeof r.pathPrepend !== "string")
      throw new InvalidPiSettingsError("`pathPrepend` must be a string");
    next.pathPrepend = normalizePathPrepend(r.pathPrepend);
  }
  if ("workdir" in r) {
    if (typeof r.workdir !== "string")
      throw new InvalidPiSettingsError("`workdir` must be a string");
    next.workdir = r.workdir.trim();
  }
  if ("model" in r) {
    if (r.model !== null && typeof r.model !== "string") {
      throw new InvalidPiSettingsError("`model` must be a string or null");
    }
    next.model = typeof r.model === "string" && r.model.trim() ? r.model.trim() : null;
  }
  if (typeof r.privateKey === "string" && r.privateKey.trim()) {
    const key = r.privateKey.trimEnd();
    if (!key.startsWith("-----BEGIN")) {
      throw new InvalidPiSettingsError("`privateKey` must be a PEM private key (-----BEGIN …)");
    }
    next.privateKey = `${key}\n`;
    // A new PEM invalidates whatever public half was on record; the service
    // re-derives it from the stored key right after saving.
    if (key !== current.privateKey?.trimEnd()) next.publicKey = null;
    // Custody is recorded, never inferred, and never claimed back: a pasted key
    // stays "pasted" until generateKeyPair replaces it.
    next.keySource = "pasted";
  }

  if (next.enabled) {
    if (!next.host)
      throw new InvalidPiSettingsError("`host` is required to enable the remote pi worker");
    if (!next.user)
      throw new InvalidPiSettingsError("`user` is required to enable the remote pi worker");
    if (!next.workdir.startsWith("/")) {
      throw new InvalidPiSettingsError("`workdir` must be an absolute path on the remote host");
    }
    if (!next.privateKey) {
      throw new InvalidPiSettingsError("a private key is required — generate one or paste a PEM");
    }
  }
  return next;
}

/** Whether a saved settings blob is complete enough to dispatch runs with. */
export function piConfigured(settings: PiSettings): boolean {
  return (
    settings.enabled &&
    settings.host !== "" &&
    settings.user !== "" &&
    settings.workdir.startsWith("/") &&
    settings.privateKey !== null
  );
}

/** `user@host`, port implicit when 22 (ssh's own default). */
export function piTarget(settings: PiSettings): string {
  return `${settings.user}@${settings.host}`;
}
